services:
  nginx:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
      target: nginx
    restart: unless-stopped
    environment:
      - NGINX_SERVER_NAME=${NGINX_SERVER_NAME:?Must set nginx server name}
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/templates:/etc/nginx/templates
      - media_files:/srv/app/media/:ro
    networks:
      - web-network

  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?Must set postgres user name}
      - POSTGRES_DB=${POSTGRES_DB:?Must set postgres database name}
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password_file
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/postgres/scripts/:/docker-entrypoint-initdb.d/
    secrets:
      - postgres_password_file
    networks:
      - db-network

  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
      target: production
    restart: unless-stopped
    environment:
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS:?Must set allowed hosts}
      - DJANGO_SECRET_KEY_FILE=/run/secrets/django_secret_key_file
      - DJANGO_LOG_LEVEL=${DJANGO_LOG_LEVEL:-WARNING}
      - DJANGO_DEFAULT_FROM_EMAIL=${DJANGO_DEFAULT_FROM_EMAIL:?Must set a default from email}
      - DJANGO_EMAIL_HOST=${DJANGO_EMAIL_HOST:?Must set an email host}
      - DJANGO_EMAIL_HOST_USER=${DJANGO_EMAIL_HOST_USER:?Must set an email host user}
      - DJANGO_EMAIL_HOST_PASSWORD=${DJANGO_EMAIL_HOST_PASSWORD:?Must set an email host password}
      - POSTGRES_USER=${POSTGRES_USER:?Must set postgres user name}
      - POSTGRES_DB=${POSTGRES_DB:?Must set postgres database name}
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password_file
      - POSTGRES_HOST=postgres
      - WAGTAILADMIN_BASE_URL=${WAGTAILADMIN_BASE_URL:?Must set admin base url}
      - WAGTAIL_SITE_NAME=${WAGTAIL_SITE_NAME:?Must set wagtail site name}
      - UMAMI_HOST=${UMAMI_HOST}
      - UMAMI_API_KEY=${UMAMI_API_KEY}
      - UMAMI_API_BASE=${UMAMI_API_BASE}
      - SENTRY_DSN_FILE=/run/secrets/sentry_dsn_file
      - BLUESKY_USERNAME=${BLUESKY_USERNAME}
      - BLUESKY_PASSWORD_FILE=/run/secrets/bluesky_password_file
    volumes:
      - media_files:/app/media/:rw
    secrets:
     - django_secret_key_file
     - postgres_password_file
     - sentry_dsn_file
     - bluesky_password_file
    networks:
      - web-network
      - db-network
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.publish_scheduled.schedule: "@hourly"
      ofelia.job-exec.publish_scheduled.command: "python manage.py publish_scheduled"
      ofelia.job-exec.publish_scheduled.user: wagtail
      ofelia.job-exec.publish_social.schedule: "@hourly"
      ofelia.job-exec.publish_social.command: "python manage.py publish_social_posts"
      ofelia.job-exec.publish_social.user: wagtail

  ofelia:
    image: mcuadros/ofelia:0.3.22
    depends_on:
      - django
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  web-network:
    name: plants-web-network
  db-network:
    name: plants-db-network
  
secrets:
  postgres_password_file:
    file: ${POSTGRES_PASSWORD_FILE:?Must set postgres password file}
  django_secret_key_file:
    file: ${DJANGO_SECRET_KEY_FILE:?Must set django secret key file}
  sentry_dsn_file:
    file: ${SENTRY_DSN_FILE:?Must set sentry dsn file}
  bluesky_password_file:
    file: ${BLUESKY_PASSWORD_FILE:?Must set bluesky password file}

volumes:
  media_files:
  db_data: