# Generated by Django 6.0.6 on 2026-06-05 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facts', '0002_facttag_taggedfact_factpage_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueskyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('bluesky_uri', models.CharField(blank=True, max_length=512)),
                ('bluesky_cid', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error', models.TextField(blank=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bluesky_post', to='facts.factpage')),
            ],
        ),
    ]
