# Generated by Django 6.0.7 on 2026-07-19 20:11

import core.models
import django.db.models.deletion
import search.models
import wagtail.fields
import wagtail.rich_text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True, help_text='Introductory content for the article index page.')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.MetadataMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(help_text='A short introduction used in article listings and social posts.', validators=[wagtail.rich_text.RichTextMaxLengthValidator(500)])),
                ('image_description', models.TextField(blank=True, help_text='The caption displayed underneath the image.', max_length=150)),
                ('image_alt', models.TextField(blank=True, help_text='Override the alt text for this image.', max_length=300)),
                ('body', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Heading'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', 'Heading 2'), ('3', 'Heading 3')]}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {})})),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=(search.models.SearchablePageMixin, core.models.MetadataMixin, core.models.RelatedPagesMixin, core.models.TaggedPageMixin, core.models.TableOfContentsPageMixin, 'wagtailcore.page'),
        ),
    ]
