# Generated by Django 6.0.8 on 2026-08-13 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepage',
            options={'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
    ]
