# Generated by Django 6.0.9 on 2026-10-10 03:28

import core.models
import django.db.models.deletion
import search.models
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0098_apitoken'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.ListingSitemapMixin, core.models.LLMsTxtListingMixin, core.models.MetadataMixin, core.models.MarkdownPageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='ImagePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('description', wagtail.fields.RichTextField()),
                ('image_description', models.TextField(blank=True, help_text='The caption displayed underneath the image.', max_length=150)),
                ('image_alt', models.TextField(blank=True, help_text="Override the image's default alt text for this page.", max_length=300)),
                ('references', wagtail.fields.StreamField([('reference', 2)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic']}), 1: ('wagtail.blocks.URLBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('label', 0), ('url', 1)]], {})}, help_text='Optional sources or further reading for this image.')),
                ('image', models.OneToOneField(help_text='The image this page describes.', on_delete=django.db.models.deletion.PROTECT, related_name='image_page', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
            bases=(search.models.SearchablePageMixin, core.models.MetadataMixin, core.models.RelatedPagesMixin, core.models.TaggedPageMixin, core.models.MarkdownPageMixin, 'wagtailcore.page'),
        ),
    ]
