# Generated by Django 6.0.9 on 2026-10-10 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.WAGTAIL_PAGE_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepage',
            name='image',
            field=models.ForeignKey(help_text='The image this page describes.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddConstraint(
            model_name='imagepage',
            constraint=models.UniqueConstraint(fields=('image',), name='unique_image_page_image'),
        ),
    ]
