# Generated by Django 6.0.9 on 2026-10-10 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_imagepage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepage',
            name='image_description',
        ),
    ]
