# Generated by Django 6.0.7 on 2026-07-19 06:19

import core.models
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TocPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('group', 5), ('paragraph', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Heading'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', 'Heading 2'), ('3', 'Heading 3')]}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {}), 4: ('wagtail.blocks.StreamBlock', [[('heading', 2)]], {}), 5: ('wagtail.blocks.StructBlock', [[('introduction', 2), ('items', 3), ('body', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {})})),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.TableOfContentsPageMixin, 'wagtailcore.page'),
        ),
    ]
