# Generated by Django 6.0.5 on 2026-05-14 06:51

import django.db.models.deletion
import wagtail.fields
import wagtail.rich_text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True, help_text='Introductory content for the fact index page.')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(help_text='The date this fact is for.', unique=True)),
                ('content', wagtail.fields.RichTextField(help_text='The content of this fact.', validators=[wagtail.rich_text.RichTextMaxLengthValidator(500)])),
                ('references', wagtail.fields.StreamField([('reference', 2)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic']}), 1: ('wagtail.blocks.URLBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('label', 0), ('url', 1)]], {})}, help_text='The references for this fact')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
