# Generated by Django 6.0.6 on 2026-06-17 14:56

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0002_facttag_taggedfact_factpage_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactPageRelatedFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='facts.factpage')),
                ('owner', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_facts', to='facts.factpage')),
            ],
        ),
    ]
