# Generated by Django 6.0.6 on 2026-07-01 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0003_factpagerelatedfact'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='factpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facts', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='factpage',
            name='image_alt',
            field=models.TextField(blank=True, help_text='Override the alt text for this image', max_length=300),
        ),
        migrations.AddField(
            model_name='factpage',
            name='image_description',
            field=models.TextField(blank=True, help_text='The caption for this image', max_length=150),
        ),
    ]
