# Generated by Django 6.0.8 on 2026-08-13 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0006_migrate_page_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factpage',
            options={'verbose_name': 'fact', 'verbose_name_plural': 'facts'},
        ),
    ]
