# Generated by Django 6.0.7 on 2026-07-24 10:32

import django.db.models.deletion
import wagtail.fields
import wagtail.models.preview
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tag_pagetag'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMsTxtSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections', wagtail.fields.StreamField([('curated', 3), ('automatic', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.PageChooserBlock', (), {}), 2: ('wagtail.blocks.ListBlock', (1,), {}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('pages', 2)]], {}), 4: ('core.blocks.LLMsTxtListingPageChooserBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('listing_page', 4)]], {})}, help_text='The ordered link sections to include in /llms.txt.')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'LLMs.txt',
            },
            bases=(wagtail.models.preview.PreviewableMixin, models.Model),
        ),
    ]
