# Generated by Django 6.0.7 on 2026-07-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_llmstxtsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='type',
            field=models.CharField(choices=[('bluesky', 'BlueSky'), ('feed', 'Feed'), ('robots', 'Robots')], default='bluesky', help_text='The type of social media link', max_length=32),
        ),
    ]
