# Generated by Django 6.0.8 on 2026-08-13 18:17

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_relatedpagesexplorerpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmstxtsettings',
            name='information',
            field=wagtail.fields.RichTextField(blank=True, help_text='Information about the site'),
        ),
    ]
