name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      
      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked

      - name: Run ruff linter
        run: uv run ruff check --output-format=github

      - name: Run ruff formatter
        run: uv run ruff format --check
      
      - name: Check template formatting
        run: git ls-files "*.html" | xargs uv run djhtml --check

      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json
      
      - name: Install npm dependencies
        run: npm ci --no-audit --fund=false

      - name: Build static assets
        run: npm run build

      - name: Run the tests
        run: uv run pytest src/ --ignore src/e2e

      - name: Install playwright
        run: uv sync --locked --group playwright && uv run -m playwright install --with-deps chromium

      - name: Run the e2e tests
        run: uv run pytest --ds dailyplant.settings.e2e -m e2e