name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked

      - name: Run ruff linter
        run: uv run ruff check --output-format=github

      - name: Run ruff formatter
        run: uv run ruff format --check
      
      - name: Check template formatting
        run: git ls-files "*.html" | xargs uv run djhtml --check

      - name: Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json
      
      - name: Install npm dependencies
        run: npm ci --no-audit --fund=false

      - name: Build static assets
        run: npm run build

      - name: Run the tests
        run: uv run pytest src/ 
